name: audio_player_with_notification_example
description: Demonstrates how to use the audioplayers plugin.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+17
  path_provider: ^0.4.1
  audio_player_with_notification:
    path: ../
flutter:
  uses-material-design: true

  assets:
    - assets/audio.mp3
    - assets/audio2.mp3

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
