name: audio_player_with_notification
description: A flutter plugin to play multiple audio files simultaneously
version: 0.8.0
author: Luan Nico <luannico27@gmail.com>
homepage: https://github.com/luanpotter/audioplayer

flutter:
  plugin:
    androidPackage: com.whaleread.audio_player_with_notification
    pluginClass: AudioPlayerPlugin

dependencies:
  uuid: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.11.3+17
  test: ^1.3.0
  path_provider: ^0.4.1

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
